### ISSUE TITLE
High CPU usage and crash

### ISSUE THREAD

**Issue by Elinvention** [DeathByDenim/PAAlternativeLauncher#1]
I am using Debian testing, I compiled the program, but it completely occupy one core of my CPU.

I ran the program through sysprof and it says that some function in file /lib/x86_64-linux-gnu/libz.so.1.2.8 is the culprit. With gdb I see it's the main thread.

When I click on `Download and install` the program crashes because of a failing assertion: `Q_ASSERT(mZstream.avail_in == 0);` in paalternativelauncher.cpp.

Also, I don't know if it's related, but whene the program starts up it shows in the terminal `QFSFileEngine::open: No file name specified`.

I am trying to investigate, but no success so far.

**Comment by DeathByDenim** [comment]
I don't run Debian Testing myself, but I installed in a virtual machine.

I tried to reproduce your issue, so I downloaded the source from GitHub, compiled it, and ran it. It came up ok and there was no CPU usage. Then I logged in and that worked fine too. Then I pressed "Download and install" and the launcher proceeded to download the entire game without crashing.

So I can't really reproduce this one. I checked the zlib package with dpkg and I also have zlib 1.2.8.dsfg-5, so presumably we use the same version as well.

Did you already have PA installed somewhere before you used the launcher? I only tested with a fresh install.

The error you get about SFQFileEngine is normal. I have since forgotten why it shows that, but it's harmless.
